import 'package:health_and_beyond/core/requests/request_constants.dart';

class DoctorProfileData {
  final String id,
      firstName,
      middleName,
      lastName,
      gender,
      dob,
      education,
      license,
      workExperience,
      mobile,
      pincode,
      city,
      state,
      address,
      password,
      uniqueId,
      email,
      hospitalName,
      workAddress,
      workPincode,
      workCity,
      workState,
      workTiming,
      workContact;

  DoctorProfileData({
    required this.id,
    required this.firstName,
    required this.middleName,
    required this.lastName,
    required this.gender,
    required this.dob,
    required this.education,
    required this.license,
    required this.workExperience,
    required this.mobile,
    required this.pincode,
    required this.city,
    required this.state,
    required this.address,
    required this.password,
    required this.uniqueId,
    required this.email,
    required this.hospitalName,
    required this.workAddress,
    required this.workPincode,
    required this.workCity,
    required this.workState,
    required this.workTiming,
    required this.workContact,
  });

  factory DoctorProfileData.toProfileData({required jsonData}) {
    return DoctorProfileData(
      id: jsonData[RequestConstants.profileId],
      firstName: jsonData[RequestConstants.profileFirstName],
      middleName: jsonData[RequestConstants.profileMiddleName],
      lastName: jsonData[RequestConstants.profileLastName],
      gender: jsonData[RequestConstants.profileGender],
      dob: jsonData[RequestConstants.profileDOB],
      education: jsonData[RequestConstants.profileEducation],
      license: jsonData[RequestConstants.profileLicense],
      workExperience: jsonData[RequestConstants.profileExp],
      mobile: jsonData[RequestConstants.profileMobile],
      pincode: jsonData[RequestConstants.profilePincode],
      city: jsonData[RequestConstants.profileCity],
      state: jsonData[RequestConstants.profileState],
      address: jsonData[RequestConstants.profileAddress],
      password: jsonData[RequestConstants.profilePassword],
      uniqueId: jsonData[RequestConstants.profileUid],
      email: jsonData[RequestConstants.profileEmail],
      hospitalName: jsonData[RequestConstants.profileHospitalName],
      workAddress: jsonData[RequestConstants.profileWorkAddress],
      workPincode: jsonData[RequestConstants.profileWorkPincode],
      workCity: jsonData[RequestConstants.profileWorkCity],
      workState: jsonData[RequestConstants.profileWorkState],
      workTiming: jsonData[RequestConstants.profileWorkTiming],
      workContact: jsonData[RequestConstants.profileWorkContact],
    );
  }
}
